all: main1 main2 main3
main1:
	g++ -std=c++11 main.cpp ComputationalGraph.cpp Tensor.cpp Operator.cpp Scalar.cpp -o main1
main2:
	g++ -std=c++11 main.cpp ComputationalGraph.cpp Tensor.cpp Operator.cpp Scalar.cpp -o main2

main3:
	g++ -std=c++11 main_Newton.cpp Scalar.cpp Operator.cpp NewtonWrapper.cpp Newton.cpp -o main3
